#!/bin/sh

export VERSION="v2.0.0-RC1"
export PLATFORMIO_EXTRA_SCRIPTS="./CreawsomeCore/rename.py"

ENV=`grep env:tr CreawsomeCore/*.ini | sed -E 's/(.*:\[env:)|(])//g'`

for env in $ENV
do args="$args -e $env"
done

pio run $args
